### ISSUE TITLE
[Bug] 滑动输入条，选择步数，和默认值，预览数目展示有问题

### ISSUE THREAD

**Issue by Henry129999** [jd-opensource/drip-form#100]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [X] I have read the console error message carefully (if applicable).

### Description

滑动输入条，选择步数，和默认值，预览数目展示有问题

![image](https://user-images.githubusercontent.com/36527485/148033459-4268cab0-03d5-4a91-86d6-f8c744ea447f.png)

### Steps to reproduce

滑动输入条，选择步数，和默认值，预览数目展示有问题

### Current behavior

滑动输入条，选择步数，和默认值，预览数目展示有问题

### Expected behavior

滑动输入条，选择步数，和默认值，预览数目展示有问题

### Your environment

- DripForm version used:
- DripFormTheme used:
- DripFormTheme version used:

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment]
非drip-form 问题，antd主题测试结果相同，参考[codeSandbox例子](https://codesandbox.io/s/ji-ben-antd-4-18-2-forked-nhd77?file=/index.js)。
我理解，step是4，默认值应该是4的倍数。
