### ISSUE TITLE
[Bug] 设置一个表单模块有多选框和数字输入框，点击数字输入框组件设置默认值后在切换到多选框报错

### ISSUE THREAD

**Issue by Henry129999** [jd-opensource/drip-form#101]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [X] I have read the console error message carefully (if applicable).

### Description

设置一个表单模块有多选框和数字输入框，点击数字输入框组件设置默认值后在切换到多选框报错

![image](https://user-images.githubusercontent.com/36527485/148033748-42d6f0c4-efc0-4edd-bab1-2fe6a704bf88.png)

### Steps to reproduce

1. 设置一个表单模块有多选框和数字输入框
2. 点击数字输入框组件设置默认值
3. 切换到多选框报错

### Current behavior

报错

### Expected behavior

不报错

### Your environment

- DripForm version used:
- DripFormTheme used:
- DripFormTheme version used:

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment]
无法复现，请确认是否使用最新版本。
使用环境需要填写
![image](https://user-images.githubusercontent.com/19370610/149108593-ba296af6-0ecc-4a71-944b-111e82f18a51.png)

确认是否 #90 导致问题，如果是，则已修复
