### ISSUE TITLE
[Bug] 修改组件报错

### ISSUE THREAD

**Issue by zty112233** [jd-opensource/drip-form#104]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [ ] I have read the console error message carefully (if applicable).

### Description

当fieldKey为'ui:description.type'这种情况，修改组件会报错：Cannot set properties of undefined (setting 'type')

<img width="863" alt="lowcode" src="https://user-images.githubusercontent.com/96771508/148358770-1ce70e72-8d96-4c5c-b9f1-523a4102491a.png">

### Steps to reproduce

当fieldKey为'ui:description.type'这种情况，修改组件会报错：Cannot set properties of undefined (setting 'type')

### Current behavior

当fieldKey为'ui:description.type'这种情况，修改组件会报错：Cannot set properties of undefined (setting 'type')

### Expected behavior

当fieldKey为'ui:description.type'这种情况，修改组件会报错：Cannot set properties of undefined (setting 'type')

### Your environment

- DripForm version used:
- DripFormTheme used:
- DripFormTheme version used:

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment]
麻烦提供可以复现的最小schema和使用的主题

**Comment by zty112233** [comment]
> 麻烦提供可以复现的最小schema和使用的主题
>>>最小schema：
{
    "fieldKey": "ui:description.type",
    "title": "是否展示提示",
    "ui:type": "radio",
    "type": "string",
    "ui:options": [
        {
            "label": "图标",
            "value": "icon"
        },
        {
            "label": "文本",
            "value": "text"
        },
        {
            "label": "隐藏",
            "value": ""
        }
    ],
    "default": "icon",
    "ui:style": {
        "width": "100%"
    }
}

>>>主题用的是antd

**Comment by mengshang918** [comment]
fieldKey暂时不支持`.` ，原因如下：
1. drip-form内部嵌套错误信息erros展现形式如下：
``` json
{
  "a.b":"错误信息"
}
```
2. 部分代码根据`.`分割获取当前fieldKey

在后续完善测试覆盖率场景后，可以支持fieldKey携带`.`。可以关注后续版本
