### ISSUE TITLE
当unitedSchema全局validateTIme为submit或click时，表单校验字段不显示

### ISSUE THREAD

**Issue by cyue177** [jd-opensource/drip-form#189]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [ ] I have read the console error message carefully (if applicable).

### Description

* 当全局validateTime设置为 submit或click时，表单校验时的错误字段不显示。
* DripForm组件中的onSubmit属性怎么使用？document中没有对应的说明。(文档中缺失的内容还挺多的)DripForm组件validatetime是submit时如何触发？
* 表单项校验为click时，点击一次之后如果有错误字段返回，该按钮就不可用了，返回空字符串是正常的。

### Steps to reproduce

1. 同上

### Current behavior

同上

### Expected behavior

* 当全局的validateTime设置为 submit或click时，表单校验时的错误字段不显示，比如必输或者错误校验字段。
* 预期为 submit时表单自带提交按钮或者回车可自动提交。
* 表单项校验为click时，点击一次之后异步校验函数中如果有错误字段返回，该按钮变为disable。此处应该为当 表单内容变更后重新恢复可点击

### Your environment

- DripForm version used:0.7.0
- DripFormTheme used:0.7.0
- DripFormTheme version used:0.7.0

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment]
首先，`DripForm`除了自定义校验部分（onValidate）是手动控制的，`ajv`校验（内置的关键字校验）都是实时校验的。`validateTime`提供的配置只是用来展示错误和不展示错误。当`validateTime`为`change`时，错误信息会直接展示。为`submit`或其他字段时，错误不会展示。
1. validateTime设置为submit，有以下几种使用方法

* 配合ref的submit方法 #85
* 配合form自带的footer按钮，DripForm可以传入onSubmit、onCancel去触发点击回调
* 通过ref获取错误信息


  由于提交时校验，有的用户不希望错误信息直接展示在表单下方，所以并没有强制展示，而是用户自己控制是否展示。
  目前可以通过以下方法去设置提交之后展示错误信息
  ```
   dispatch({
            type:'setValidate',
            action:{
              set:{
                validateTime:'change'
              }
            }
          })
  ```

2. onValidate type为click时，按钮的disabled状态由当前表单的错误信息控制，有错误就会disabled。如果是异步校验，确实不合理。对于ajv校验是合理的

    我理解如果是按钮置灰可以分几种情况：
   * 同时存在ajv内置校验错误和自定义校验错误
    解决ajv错误之后，按钮立即撤销置灰
   * 只存在ajv内置校验错误
   只有解决错误之后，按钮才撤销置灰
   * 只存在自定义错误
 变更数据，按钮撤销置灰

3. 文档完善问题，可在#65 中讨论希望完善的文档
DripForm在v0.8.0发布之后，会对文档进行重构并完善测试用例

**Comment by cyue177** [comment]
form自带的footer按钮怎么使用？怎么配置按钮才会展示？

**Comment by mengshang918** [comment]
> form自带的footer按钮怎么使用？怎么配置按钮才会展示？

可以在generator中全局有个底部按钮进行配置。
![image](https://user-images.githubusercontent.com/19370610/163511609-350a1917-bfe0-4546-8441-3116998abd14.png)
