### ISSUE TITLE
./node_modules/@monaco-editor/react/dist/index.mjs

### ISSUE THREAD

**Issue by hqylss111** [jd-opensource/drip-form#263]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Description

./node_modules/@monaco-editor/react/dist/index.mjs
Can't import the named export 'memo' from non EcmaScript module (only default export is available)
无法从非 EcmaScript 模块导入指定的导出“备忘录”（只有默认导出可用）

webpack版本5.0 
"react": "^17.0.2",
    "react-app-polyfill": "^2.0.0",
    "react-dev-utils": "^11.0.3",
    "react-dom": "^17.0.2",

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by mengshang918** [comment]
可以提供一下复现的demo，方便排查。

**Comment by hqylss111** [comment]
这个解决了 是你的子包里面的 @monaco-editor/react 这个包存在版本问题。 要么锁定子包版本 要么要更新最新版本。  不支持es module

**Comment by mengshang918** [comment]
使用的版本是啥？可以使用最新的alpha版本试一试，如果还是有问题，可以提供复现demo或者提供pr。感谢

**Comment by hqylss111** [comment]
使用的版本是^0.8.0
原库问题解答： https://github.com/suren-atoyan/monaco-react/issues/477#issuecomment-1531837265 
目前使用的是4.4.6.
resolutions":{
    "@monaco-editor/react": "4.4.6"
  } 使用的yarn 锁定子版本解决的问题。
