### ISSUE TITLE
[Bug] <在对象容器中使用组件，默认值会失效>

### ISSUE THREAD

**Issue by 1379255913** [jd-opensource/drip-form#280]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [X] I have read the console error message carefully (if applicable).

### Description

在对象容器中使用组件，默认值会失效
![image](https://github.com/jd-opensource/drip-form/assets/100053992/b06ed0cd-e9a0-4025-b19f-15a5c00a8dcc)
![image](https://github.com/jd-opensource/drip-form/assets/100053992/d7c275e6-b6da-456d-bb74-1bdfec96df00)

### Steps to reproduce

1. Generator中创建一个对象容器
2. 在对象容器中任意添加一个组件，并设置默认值
3. 默认值失效，从对象容器中取出至最外层时，默认值出现

### Current behavior

在对象容器中使用组件，默认值会失效

### Expected behavior

在对象容器中使用组件，默认值依然生效

### Your environment

- DripForm version used: 0.9.0-alpha.20
- DripFormTheme used: 0.9.0-alpha.20
- DripFormTheme version used: 0.9.0-alpha.20

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment]
参考[数组、对象设置默认值](https://jd-opensource.github.io/drip-form/docs/form/advanced/otherInternal/default#%E6%95%B0%E7%BB%84%E5%AF%B9%E8%B1%A1%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E5%80%BC)
