### ISSUE TITLE
[Bug] <title> monaco-editor init error

### ISSUE THREAD

**Issue by pk111and222** [jd-opensource/drip-form#41]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [ ] I have read the console error message carefully (if applicable).

### Description

When the editor initializes, it initializes the wrong initialization, monaco-editor init error

### Steps to reproduce

1、open project
2、click preview error

### Current behavior

none

### Expected behavior

none

### Your environment

- DripForm version used: 0.2.0-alpha.1
- DripFormTheme used: 0.2.0-alpha.1
- DripFormTheme version used: 0.2.0-alpha.1

### Self-service

- [x] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment]
By default, it loads monaco sources from CDN（https://cdn.jsdelivr.net/npm/monaco-editor@0.30.1/min/vs）. We modified the CDN address to JD（https://storage.360buyimg.com/bird/dripform）
See [monaco-loader](https://github.com/suren-atoyan/monaco-loader#for-electron-users) for details
