### ISSUE TITLE
自定义组件内设置$:type后，在渲染时报错 strict mode: unknown keyword: "$:type"

### ISSUE THREAD

**Issue by urnwangss** [jd-opensource/drip-form#43]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [ ] I have read the console error message carefully (if applicable).

### Description

自定义组件内设置$:type后，在渲染时报错 strict mode: unknown keyword: "$:type"

### Steps to reproduce

自定义组件内设置$:type后，在渲染时报错 strict mode: unknown keyword: "$:type"

### Current behavior

自定义组件内设置$:type后，在渲染时报错 strict mode: unknown keyword: "$:type"

### Expected behavior

自定义组件内设置$:type后，在渲染时报错 strict mode: unknown keyword: "$:type"

### Your environment

- DripForm version used:
- DripFormTheme used:
- DripFormTheme version used:

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment]
我们需要先通过parseUnitedSchema解析有哪些自定义关键字 @KingGanZeng

**Comment by KingGanZeng** [comment]
parse新增字段customProps，包含unitedSchema中的所有 `$:` 开头的属性
如果有 `ui:$:xxx` 这种的也会收集，但是为了统一会把前面的ui去掉

**Comment by mengshang918** [comment]
> parse新增字段customProps，包含unitedSchema中的所有 `$:` 开头的属性 如果有 `ui:$:xxx` 这种的也会收集，但是为了统一会把前面的ui去掉

可以不涉及ui里面字段吗？ajv无需关心ui属性。我们可以只对解析出来后的dataSchema作解析处理。或者在parseUnitedSchema中针对dataSchema做$:开头的自定义属性作处理

**Comment by KingGanZeng** [comment]
> > parse新增字段customProps，包含unitedSchema中的所有 `$:` 开头的属性 如果有 `ui:$:xxx` 这种的也会收集，但是为了统一会把前面的ui去掉
> 
> 可以不涉及ui里面字段吗？ajv无需关心ui属性。我们可以只对解析出来后的dataSchema作解析处理。或者在parseUnitedSchema中针对dataSchema做$:开头的自定义属性作处理

修改了这部分逻辑，目前只收集dataSchema中的
