### ISSUE TITLE
[Bug] <title>form-generator 在使用object嵌套object时页面报错了

### ISSUE THREAD

**Issue by guojinchao** [jd-opensource/drip-form#46]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [ ] I have read the console error message carefully (if applicable).

### Description

我在可视化区域使用了object对象组, 在对象组内嵌套一个对象组时,页面报错变成了白页

### Steps to reproduce

1. 使用drip-form编译器
2. 拖拽对象组
3. 拖拽新的对象组到原对象组内

### Current behavior

可能是object内处理复杂的结构出现了问题

### Expected behavior

我想在编译器内可以嵌套使用深层结构

### Your environment

- DripForm version used:
- DripFormTheme used:
- DripFormTheme version used:

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment]
无法复现，请描述更详细的复现场景，或者截图、视频

**Comment by guojinchao** [comment]
https://user-images.githubusercontent.com/22298505/146895378-a19a64f4-b637-40ef-84cc-4c2bda584783.mp4




![image](https://user-images.githubusercontent.com/22298505/146895323-95543068-e719-4ff1-9060-aa003fe32b76.png)
