### ISSUE TITLE
form-generator 使用编译器添加组建时新增的表单总会出现在最上面

### ISSUE THREAD

**Issue by guojinchao** [jd-opensource/drip-form#47]
### Is your feature request related to a problem? Please describe.

在我使用form-generator时 每次新增的表单项在最上面出现, 我需要再重新拖动, 并不友好

### Description

在我使用form-generator时 每次新增的表单项在最上面出现, 我需要再重新拖动, 并不友好

### Describe the solution you'd like

是否可以按照我添加的顺序依次往下排列

### Self-service

- [ ] I'd be willing to contribute this feature to DripForm myself.

**Comment by guojinchao** [comment]
https://user-images.githubusercontent.com/22298505/146895007-70e92686-2166-4e52-b1ff-2e95c3e33e96.mp4

![image](https://user-images.githubusercontent.com/22298505/146895124-8e76e318-be23-446d-82fc-c889bae48022.png)

**Comment by mengshang918** [comment]
#147 support
