### ISSUE TITLE
contributors

### ISSUE THREAD

**Issue by mengshang918** [jd-opensource/drip-form#5]
People are giving themselves and their free time to contribute to open source projects in so many ways, so we believe everyone should be praised for their contributions (code or not).

`Drip form` follows [all-contributors](https://allcontributors.org/docs/en/specification) specification. 

Write a comment on an issue or pull request to recognise their contribution.
`@all-contributors please add @<username> for <contributions>`

 For example:
`@all-contributors please add @mengshang918 for code ✨`

For more information, please see [all-contributors contributions]( https://allcontributors.org/docs/en/emoji-key)

**Comment by mengshang918** [comment]
@all-contributors add @KingGanZeng for code,bug,doc,example,ideas

**Comment by mengshang918** [comment]
@all-contributors add @KingGanZeng for code bug doc example and ideas

**Comment by mengshang918** [comment]
@all-contributors add @yirenliancheng  for doc

**Comment by mengshang918** [comment]
@all-contributors add @xinysongxixi for code bug

**Comment by mengshang918** [comment]
@all-contributors add @Henry129999 for bug

**Comment by mengshang918** [comment]
@all-contributors add @CrazyWood007  for docs code

**Comment by mengshang918** [comment]
@all-contributors add @helloqian12138  for bug code

**Comment by mengshang918** [comment]
@all-contributors add @scizorrr  for docs ideas

**Comment by mengshang918** [comment]
@all-contributors add @sum324 for docs design

**Comment by mengshang918** [comment]
@all-contributors add @tinymins for bug code

**Comment by mengshang918** [comment]
@all-contributors add @RelaxLiu for code

**Comment by KingGanZeng** [comment]
so sweet!

**Comment by mengshang918** [comment]
@all-contributors add @RelaxLiu for design

**Comment by mengshang918** [comment]
@all-contributors add @Too-Tao for code docs bug

**Comment by guojinchao** [comment]
@all-contributors add @guojinchao  for code doc ideas
