### ISSUE TITLE
[Bug] 图片组件 maxiumn 不能配置的问题

### ISSUE THREAD

**Issue by changweijie** [jd-opensource/drip-form#50]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [X] I have read the console error message carefully (if applicable).

### Description

 图片组件 maxiumn 不能加，加了就没有图片预览效果了。

### Steps to reproduce

1. 图片上传组件添加了 maxium属性

### Current behavior

不能预览

### Expected behavior

可以预览

### Your environment

- DripForm version used:
- DripFormTheme used:
- DripFormTheme version used:

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment]
无法预览和drip-form无关，参考 使用主题是否支持预览：[antd upload api](https://ant.design/components/upload-cn/#API)

**Comment by mengshang918** [comment]
antd v4.10.0支持maxCount配置最大上传数量，@jdfed/drip-form-theme-antd在antd v4.10.0之前使用maxFileNumber配置。统一为maxCount，并兼容maxFileNumber
