### ISSUE TITLE
【数组容器】数组容器的添加一行这里是不是文案可以定制

### ISSUE THREAD

**Issue by changweijie** [jd-opensource/drip-form#51]
### Is your feature request related to a problem? Please describe.

【数组容器】数组容器的添加一行这里是不是文案可以定制

### Description

【数组容器】数组容器的添加一行这里是不是文案可以定制

### Describe the solution you'd like

文案可定制

### Self-service

- [ ] I'd be willing to contribute this feature to DripForm myself.

**Comment by mengshang918** [comment]
```
{
  "validateTime": "change",
  "type": "object",
  "ui": {},
  "theme": "antd",
  "schema": [
    {
      "validateTime": "submit",
      "type": "array",
      "title": "数组容器",
      "ui": {
        "type": "array",
        "mode": "add",
        "addTitle": "新增一行"
      },
      "fieldKey": "array_pEK2BH"
    }
  ]
}
```
drip-form 已经支持该功能。ui中配置addTitle
generator需要支持配置该文案，进度参考 #56 。
