### ISSUE TITLE
【feature】图片上传后拿到的是对象、目前我们在代码里处理获取上传的url, 是否可以直接输出url 

### ISSUE THREAD

**Issue by changweijie** [jd-opensource/drip-form#52]
### Is your feature request related to a problem? Please describe.

图片上传后拿到的是对象、目前我们在代码里处理获取上传的url, 是否可以直接输出url 

### Description

图片上传后拿到的是对象、目前我们在代码里处理获取上传的url, 是否可以直接输出url 

### Describe the solution you'd like

图片上传后拿到的是对象、目前我们在代码里处理获取上传的url, 是否可以直接输出url 

### Self-service

- [ ] I'd be willing to contribute this feature to DripForm myself.

**Comment by mengshang918** [comment]
目前有两种方案支持修改数据
1. 使用transform和parse中对表单数据进行处理。
2. ~使用afterAction对数据进行处理~
~或许我们需要使transform和parse可以单独针对某一项做改动（参考：#69）~
3. 属性配置添加转换string类型字段
目前存在的问题，由于upload组件存在上传一个文件和多个文件的情况，upload组件默认是object类型。如果需要默认转换为string类型，那JSONSchema当前组件的type就是['string','object','array']。当type是多类型的时候，对typeMap和generator的使用dataSchema.type的地方有影响。typeMap影响到get、set、merge等dispatch语法糖函数。我们需要在任何情况下保证获取表单数据都是string，需要对以上函数做处理。考虑到后期可能支持 #69 提议，改动影响较大。详细设计方案后同 #69 一起进入开发。开发进度可关注当前issue或 #69 提议

总结：目前可以先采用方案一实现，后续等方案三支持后可以切换

**Comment by mengshang918** [comment]
#117 已支持配置exportToString转换string
