### ISSUE TITLE
[Bug]  数组组件中删除第一个数据会把第二个数据删除

### ISSUE THREAD

**Issue by changweijie** [jd-opensource/drip-form#53]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [ ] I have read the console error message carefully (if applicable).

### Description

数组组件中删除第一个数据会把第二个数据删除

### Steps to reproduce

数组组件中删除第一个数据会把第二个数据删除

### Current behavior

数组组件中删除第一个数据会把第二个数据删除

### Expected behavior

数组组件中删除第一个数据会把第一个数据删除

### Your environment

- DripForm version used:
- DripFormTheme used:
- DripFormTheme version used:

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment]
无法复现，请提供，form版本和主题版本

**Comment by changweijie** [comment]
数组容器里面有uploader组件的时候复现
