### ISSUE TITLE
Feature:图片上传，没有校验

### ISSUE THREAD

**Issue by wcqftd** [jd-opensource/drip-form#57]
### Is your feature request related to a problem? Please describe.

need

### Description

图片上传，尺寸校验，图片大小校验没有

### Describe the solution you'd like

--

### Self-service

- [X] I'd be willing to contribute this feature to DripForm myself.

**Comment by mengshang918** [comment]
校验方案有以下两种：
1. jsonSchema中定义dimension、size关键字
   * jsonSchema是用来校验json的。不适合校验file类型。
   * 目前uploader组件是一个对象，后续可能需要支持string（参考：#52）
     string类型是一个url，这时需要校验图片尺寸。dimension可以校验；size需要fetch获取图片url 字节来判断；前端校验已经可以在beforeupload获取file对象，获取到url已经是调用上传接口之后了，这不满足校验的前置要求；而后端图片上传接口校验也不会通过url去校验。
 
2. uiprop中定义dimension、size属性
    beforeupload中校验
    问题是如何配置错误信息🤔️

总结：目前来说，方案一添加jsonSchema关键字来校验uploader这种特殊类型的是不合适的，最终采用方案二。方案二目前自动根据dimension、size配置生成错误文案，后续需要确认是否存在自定义错误文案场景
