### ISSUE TITLE
左侧组件区能否设置成可以拉动的，目前如果组件的名称稍微长一点，比如6个汉字的话，样式就很奇怪了，这个看能否修复下

### ISSUE THREAD

**Issue by urnwangss** [jd-opensource/drip-form#61]
### Is your feature request related to a problem? Please describe.

左侧组件区能否设置成可以拉动的，目前如果组件的名称稍微长一点，比如6个汉字的话，样式就很奇怪了，这个看能否修复下

### Description

左侧组件区能否设置成可以拉动的，目前如果组件的名称稍微长一点，比如6个汉字的话，样式就很奇怪了，这个看能否修复下

### Describe the solution you'd like

左侧组件区能否设置成可以拉动的，目前如果组件的名称稍微长一点，比如6个汉字的话，样式就很奇怪了，这个看能否修复下

### Self-service

- [ ] I'd be willing to contribute this feature to DripForm myself.

**Comment by mengshang918** [comment]
generator 自定义组件文案目前最多支持5个。
如果超出，希望文案hover滚动展示？超出隐藏，hover展示更详细内容？或者两者都支持，可以全局配置展示形式？
是否有更好的想法
