### ISSUE TITLE
Document needs to be completed

### ISSUE THREAD

**Issue by CrazyWood007** [jd-opensource/drip-form#65]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Description

文档中缺少一些配置项的说明，需要补全。
The description of some configuration items is missing in the document and needs to be completed.

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by mengshang918** [comment]
## DripForm部分

- 完善DripForm prop介绍和用法
 
  - [ ] containerHoc
  - [ ] onSubmit、onCancel
  - [ ] ....

- 完善footer按钮文档
- 自定义组件、自定义主题
  -  useField介绍

## DripFormGenerator部分

- ...
