### ISSUE TITLE
[Bug] 首个组件删除按钮部分被遮挡，样式需要优化一下

### ISSUE THREAD

**Issue by Henry129999** [jd-opensource/drip-form#66]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [ ] I have read the console error message carefully (if applicable).

### Description

首个组件删除按钮部分被遮挡，样式需要优化一下，提高易用性和美观性

### Steps to reproduce

新增第一个组件，第一个组件的删除按钮被部分遮挡

![image](https://user-images.githubusercontent.com/36527485/147310604-8d2c7119-9b0f-40cb-8a83-fc097f81db1f.png)

### Current behavior

首个组件删除按钮部分被遮挡

### Expected behavior

首个组件删除按钮完整展示

### Your environment

- DripForm version used:  latest version

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment]
原因：overflow 导致bfc，子元素的absolute无法超出；
解决：第一个元素的action bar展示在下方，其他元素展示在上方
