### ISSUE TITLE
属性和校验配置 设置必填之后，在没有填写的情况下也能提交成功，没有展示必填的文案

### ISSUE THREAD

**Issue by urnwangss** [jd-opensource/drip-form#87]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [ ] I have read the console error message carefully (if applicable).

### Description

属性和校验配置 设置必填之后，在没有填写的情况下也能提交成功，没有展示必填的文案

### Steps to reproduce

属性和校验配置 设置必填之后，在没有填写的情况下也能提交成功，没有展示必填的文案

### Current behavior

属性和校验配置 设置必填之后，在没有填写的情况下也能提交成功，没有展示必填的文案

### Expected behavior

属性和校验配置 设置必填之后，在没有填写的情况下也能提交成功，没有展示必填的文案

### Your environment

- DripForm version used:
- DripFormTheme used:
- DripFormTheme version used:

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment]
请填写environment使用版本，并详细描述复现路径或者视屏。否则该issue将会自动关闭
